### ISSUE TITLE
Integration with blockchain (tendermint)

### ISSUE THREAD

**Issue by LeeBlues** [jackpal/Taipei-Torrent#120]
I think  integration of Taipei-Torrent with Tendermint blockchain technology(https://github.com/tendermint/) would be great.
 Both technology is written in go-lang. I'm about to launch Tendermint based blockchain(luna-blockchain) .if it meets with Taipei-Torrent, then It can solve the economic incentive problem of seeder. ( Through the way that seeder  submit proof of seeding to blockchain). Although I need to read and understand Taipei-Torrnet code further, but since Tendermint consensus engine can generate decentralized  immutable consensus about almost anything, It can also generate decentralized consensus about which torrent file is honest one. So it can also solve malicious/fake torrent problem too I think. Any idea?

**Comment by jackpal** [comment]
I don't currently have any interest in blockchain technology. But you're welcome to use Taipei-torrent code in your own projects, as long as you respect the license.
