### ISSUE TITLE
keepalived msg,  empty msg,  also read msg len: 1,  why do this?

### ISSUE THREAD

**Issue by hongli-my** [jackpal/Taipei-Torrent#122]
https://github.com/jackpal/Taipei-Torrent/blob/3696397cc61563e7e996b612af7d9e0bd8d21e1c/torrent/peer.go#L288

**Comment by nictuku** [comment]
buf = make([]byte, n)

will not allocate more than 130kb, as per the check in line 280.

The empty message case is a keep-alive. That is, it exists to keep the connection between the peers active, even though there hasn't been any messages flowing.

It is handled here: https://github.com/jackpal/Taipei-Torrent/blob/3696397cc61563e7e996b612af7d9e0bd8d21e1c/torrent/torrent.go#L983

**Comment by hongli-my** [comment]
I know your means,  but,  if msg is none, why do this 
```
buf = make([]byte, 1) 
....
_, err = io.ReadFull(p.conn, buf);  
```
Read from conn  and len(buf) !=0 ?

**Comment by jackpal** [comment]
I think Hongli is correct, I must have misunderstood the format of
keep-alive messages when I originally wrote the code.

**Comment by nictuku** [comment]
My guess is you tried to use the extra zero byte as an internal sentinel value rather than something you'd actually read from the buffer.
