### ISSUE TITLE
DHT won't work without torrent?

### ISSUE THREAD

**Issue by ebuchman** [jackpal/Taipei-Torrent#63]
I've noticed TT only connects to peers found using the DHT if we already have the torrent file.  But what if we don't have the torrent file and only the infohash?

eg of the restriction: https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/torrent.go#L520

Even if I remove all such restrictions like this (I think there are 2 more of them), I still can't download using just an infohash, for example "magnet:?xt=urn:btih:deca7a89a1dbdc4b213de1c0d5351e92582f31fb", even though I can connect to peers found over the dht for it (and there are several).

What's the deal?

**Comment by Zilog8** [comment]
PR #89 should fix this issue (As the saying goes, "works on my machine"). Anyone who has had this problem, can you try to reproduce and confirm it works now?

**Comment by geoah** [comment]
Works as expected. :+1: Thanks a mil :)

**Comment by Zilog8** [comment]
Cool, then I'm closing this issue :-)
