### ISSUE TITLE
Embedding Taipei-Torrent

### ISSUE THREAD

**Issue by pquerna** [jackpal/Taipei-Torrent#71]
A couple functions like `ListenForPeerConnections` and `(*TorrentSession).AcceptNewPeer` take a `btConn` struct, but this struct is not exported, while these functions are public.  Change `btConn` to `BtConn`, even with all of its fields filtered would be fine?

**Comment by jpillora** [comment]
+1

A nice implementation of a pure torrent engine is https://github.com/mafintosh/torrent-stream though it's JavaScript (Node). It can list files within torrents, then selectively download ranges of those files, using quite a simple API:

``` js
var torrentStream = require('torrent-stream');

var engine = torrentStream('magnet:my-magnet-link');

engine.on('ready', function() {
    engine.files.forEach(function(file) {
        console.log('filename:', file.name);
        var stream = file.createReadStream();
        // stream is readable stream to containing the file content
    });
});
```

It'd be awesome if we could use this type of API in our own Go apps.

**Comment by jpillora** [comment]
Sorry for the spam. I just noticed that the referenced PR had been merged, which means this is possible now, I presume? Are there any examples of simple programmatic use?
