### ISSUE TITLE
String 2 Bytes

### ISSUE THREAD

**Issue by LivingInPortal** [jackpal/Taipei-Torrent#77]
Ref: https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/torrent.go#L66
Code:
```Go
func string2Bytes(s string) []byte { return bytes.NewBufferString(s).Bytes() }
```
Why not just
```Go
[]byte(YourString)
```

**Comment by nictuku** [comment]
Ha! Good one. 

Please send a PR? TT was written a zillion years ago when nobody really knew Go properly. :-P

**Comment by LivingInPortal** [comment]
Done
#79
